apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: dev
data:
  POC_SERVICE_INVENTORY_HOST: 'wsrestgestioncarrito'
  POC_SERVICE_INVENTORY_PORT: '443'
  POC_SERVICE_SECURITY_HOST: 'wsrestsecurity'
  POC_SERVICE_SECURITY_PORT: '443'
  POC_SERVICE_AUDIT_HOST: 'wsrestauditoriaapi'
  POC_SERVICE_AUDIT_PORT: '443'
