export const environment = {
  production: true,
  URLAmazon: "https://sophosstore.net/callback",
  URLCatalog: "https://iofb7ey9ig.execute-api.us-east-2.amazonaws.com",
  URLSecurity: "https://mdqv65vxdd.execute-api.us-east-2.amazonaws.com",
  URLCard: "https://gz3pccmad9.execute-api.us-east-2.amazonaws.com",
  URLOrder: "https://47av2kc0ya.execute-api.us-east-2.amazonaws.com",
  URLPayment: "https://7dfcrahihj.execute-api.us-east-2.amazonaws.com",
  endPointCatalog: "/api/products/catalog/",
  endPointDetailProduc: "/api/products/product/",
  endPointReserveProduct: "/api/products/reserve/",
  endPointGenerateToken: "/services/security/getJwtToken/",
  endPointVerifyToken: "/services/security/verifyJwtToken/",
  endPointUpdateCart: "/gestioncarrito/updatecart/",
  endPointGetCart: "/gestioncarrito/getcart/",
  endPointGetPayment: "/api/payment/add",
  endPointGetOrder: "/api/orden/add",
};
